# Generated by Django 5.2.13 on 2026-04-14 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('safeguarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='safeguardingcase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safeguarding_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='safeguardingcase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_safeguarding_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
