# Generated by Django 5.2.13 on 2026-04-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('engagement_score', models.IntegerField(default=0)),
                ('rag_status', models.CharField(choices=[('Green', 'Green'), ('Amber', 'Amber'), ('Red', 'Red')], default='Green', max_length=10)),
                ('last_contact', models.DateField(blank=True, null=True)),
                ('concerns', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
