# Generated by Django 5.2.13 on 2026-04-14 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('file_url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('linked_learner_id', models.CharField(blank=True, max_length=100)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('ofsted_theme', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='employers.employer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
